### ISSUE TITLE
No such file or directory: 'AnimalWell.sav'

### ISSUE THREAD

**Issue by onlineporno** [apocalyptech/pyanimalwell#5]
"No such file or directory: 'AnimalWell.sav'"

Hi. I get that error when just try 'awsave AnimalWell.sav -i'
**Where shoud i put my save file for script found it ?**

Full error here 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\OnLiNe\AppData\Local\Programs\Python\Python312\Scripts\awsave.exe\__main__.py", line 7, in <module>
  File "C:\Users\OnLiNe\AppData\Local\Programs\Python\Python312\Lib\site-packages\animalwellsave\cli.py", line 1357, in main
    with Savegame(args.filename) as save:
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\OnLiNe\AppData\Local\Programs\Python\Python312\Lib\site-packages\animalwellsave\savegame.py", line 1908, in __init__
    with open(self.filename, 'rb') as read_df:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'AnimalWell.sav'

**Comment by IvanStoychev** [comment]
When executing `awsave AnimalWell.sav -i` you are telling the script to work on a file called `AnimalWell.sav` which is to be located in the current directory (or the directory the script runs in, but that depends).

To fix this error provide the full path to the save file you wish to edit, ex:
`awsave 'C:\Users\OnLiNe\AppData\LocalLow\Billy Basso\Animal Well\AnimalWell.sav' -i`

**Comment by apocalyptech** [comment]
Heya; I see I never really did anything with this.  Yeah, you've gotta know where exactly the savefiles are, and then either use the full path when running the command (as @IvanStoychev provided up there), or use `cd` to get "into" the same directory as the saves, and run the command from there.

I did just add in some info on the README about finding saves (see #8), at least, though a full HOWTO on working with things on the commandline is probably outside the remit of the documentation here.  :)  Cheers!
